name: pagination_with_bloc
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  injectable: ^1.5.0
  injectable_generator: ^1.5.2
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
